### ISSUE TITLE
[Feature] Curios support

### ISSUE THREAD

**Issue by MaxWasUnavailable** [MoonflowerTeam/locksmith#27] opened 2023-04-11 02:44 UTC
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
Being able to store a key or keyring in a curios slot - either an existing one (ring / bracelet / "any"), or a specific slot, would prevent users from having to use an inventory slot on a keyring, and would save time having to move the keyring between your main inventory and toolbar (or save a toolbar slot).
```

### latest.log

```shell
Not applicable
```

**Comment by jacksonhardaway** [comment] 2023-04-11 20:26
Duplicate of #23

**Closed as completed by jacksonhardaway** 2023-04-11 20:26 UTC
